### PR TITLE
Adding parachains typeDef to the proxy schema and some refactoring

### PR DESCRIPTION
**Pull request by franjs**
This PR only adds the `typeDef` for parachains and the `ParachainsInfo` resolver. Also as part of this PR the `@polkadot/api` library was updated and some refactoring was done to introduce services to extract some logic from the resolvers that need to be reused

### CODE REVIEW

**Comment by ishrak-imam** [comment]
Are you planning to merge it without the remaining two resolvers?

**Review by ishrak-imam — APPROVED** [review]
LGTM

**Comment by franjs** [comment]
> Are you planning to merge it without the remaining two resolvers for now?

Yes, we need can wait until we found a solution to get the parachains extra info from `@polkadot/apps-config`

**Comment by franjs** [comment]
I have merged this manually due to merging conflicts

**Pull request closed without merging**
